spring.datasource.url=jdbc:mysql://localhost:3306/smartcare_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=8080
# Không sử dụng context-path để views có thể access từ root URL
# Thay vào đó, API endpoints sẽ sử dụng @RequestMapping("/api/v1/...")
# Ép Spring văng lỗi NoHandlerFoundException thay vì trả về cục HTML 404
spring.web.resources.add-mappings=false
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thời gian sống của Token: 86400000 ms = 24 giờ
jwt.expiration=86400000

# ===============================
# EMAIL CONFIGURATION (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenkhoa0914044556@gmail.com
spring.mail.password=ehdcqohcynwdfcsq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true